title: They Might Be Ghosts!
# email: contact@theymightbeghosts.com
description: >-
  Improvisors celebrating life, here and in the hereafter
baseurl: ""
url: "https://theymightbeghosts.com"
author:
  name: "They Might Be Ghosts"

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
